apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-backend"
spec:
  selector:
    app: erpnext-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.backendPort | quote }}
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-frontend"
spec:
  selector:
    app: erpnext-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.frontendPort | quote }}
      targetPort: 80
  type: "{{ .Values.service.type }}"
